In [1]:
import numpy as np 
import sys 
import time

l = range(2000)
print(sys.getsizeof(5)*len(l)) # list

array1 = np.arange(2000) #numpy array print(array1.size*array1.itemsize)

56000


In [2]:

size=10000

l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

start=time.time()           #python list
result=[x+y for x,y in zip(l1,l2)]
print("python list time",(time.time()-start)*1000)

start=time.time()        #numpy array
result=a1+a2
print("python numpy array time",(time.time()-start)*1000)

python list time 1.0030269622802734
python numpy array time 21.794557571411133


In [3]:
import pandas as pd
user_data = {'first_name': ['Aman', 'Neha', np.nan, 'Rebha'],
'last_name': ['sharma', 'bedi', np.nan, 'kapoor'],
'online': [True, np.nan, False, True],
'followers': [987, 432, 321, np.nan]}

df = pd.DataFrame(user_data, columns = ['last_name', 'first_name', 'online', 'followers'])
print(df)

  last_name first_name online  followers
0    sharma       Aman   True      987.0
1      bedi       Neha    NaN      432.0
2       NaN        NaN  False      321.0
3    kapoor      Rebha   True        NaN


In [4]:
dropcols = df.dropna()      #drop all rows which contain atleast one nan value 
print(dropcols) 

  last_name first_name online  followers
0    sharma       Aman   True      987.0


In [5]:
x = df.dropna(how ="all")
print(x) #columns which have np.nan will get deleted.

  last_name first_name online  followers
0    sharma       Aman   True      987.0
1      bedi       Neha    NaN      432.0
2       NaN        NaN  False      321.0
3    kapoor      Rebha   True        NaN


In [6]:
fillval = df.fillna(0)
print(fillval)      #if we want to write 0 in those columns which have nan

  last_name first_name online  followers
0    sharma       Aman   True      987.0
1      bedi       Neha      0      432.0
2         0          0  False      321.0
3    kapoor      Rebha   True        0.0


# data type in numpy


In [7]:
a=np.array([1,3,4,5])
print(a)
a.dtype



[1 3 4 5]


dtype('int32')

In [8]:
b=np.array([1.3,4,3,3],dtype=np.float32)
b.dtype

dtype('float32')

In [9]:
b=np.array([1.3,4,3,3])
b.dtype

dtype('float64')

In [10]:
a=np.array([1,3,4,5],dtype=np.bool)
a.dtype

dtype('bool')

In [11]:
a=np.array([1,3,4,5],dtype=np.int)    #int8, int16, int32, int64, int128, int i
a.dtype

dtype('int32')

In [12]:
a=np.array([1,3,4,5],dtype=np.uint)         #uint8, uint16, uint32, uint64,uint128, uint

a.dtype

dtype('uint32')

In [13]:
a=np.array([1,3,4,5],dtype=np.float)       #float32, float64, float, longfloat,
a.dtype

dtype('float64')

In [14]:
a=np.array([1,3,4,5],dtype=np.complex)         #complex64, complex128, complex
print(a.dtype)
a

complex128


array([ 1.+0.j,  3.+0.j,  4.+0.j,  5.+0.j])

In [15]:
a=np.array([1,3,4,5],dtype=np.object)       #object 
a.dtype

dtype('O')

In [16]:
a=np.array([1,3,4,5],dtype=np.str)       #str, unicode
a.dtype

dtype('<U1')

# array creation

In [17]:
 np.array([1,2,3,4])

array([1, 2, 3, 4])

In [18]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,1,6)    #(startpoint,end point, step size)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

# ndarray creation

In [20]:
np.zeros((2,3)) 
a = np.random.random((2,6))
print (a)

[[ 0.70661867  0.81058065  0.36779005  0.10294672  0.10037494  0.13848136]
 [ 0.86662573  0.3407911   0.36630189  0.62795405  0.33177138  0.86548644]]


In [21]:
a=np.ones((3,3))
print(a)
a=a*4
a




[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


array([[ 4.,  4.,  4.],
       [ 4.,  4.,  4.],
       [ 4.,  4.,  4.]])

In [22]:
a=np.array((2,3))
print(a)

[2 3]


In [23]:
a.transpose()

array([2, 3])

In [24]:
c = np.arange(24)
print(c)

c=c.reshape(4,3,2) 
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [25]:
c.ndim     # tell the dimensions of an array

3

In [26]:
c.shape    #tell the shape of an array

(4, 3, 2)

In [27]:
c.size     #tell the size of an array

24

In [28]:
c.dtype    #tell the data type of an array

dtype('int32')

In [29]:
c.itemsize    #tell the item size of an array

4

In [30]:
c.nbytes    #tell the total size  of an array

96

# Numpy – Creating vectors(1-D array)

In [31]:
a=np.array([1,3,5,6])
b=np.array([1,1,1,9])
c=a+b
print(c)

c=a-b
print(c)

c=a*b
print(c)

c=a%b          # for reminder
print(c)

c=a/b          # for proper division
print(c)

c=a//b      # for integer division
print(c)

c=a**b      # here b is power of a
print(c)

[ 2  4  6 15]
[ 0  2  4 -3]
[ 1  3  5 54]
[0 0 0 6]
[ 1.          3.          5.          0.66666667]
[1 3 5 0]
[       1        3        5 10077696]


In [32]:
i = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] 
c=np.array(i,dtype=complex)
print(c)

[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 3.+0.j  6.+0.j  9.+0.j]
 [ 2.+0.j  4.+0.j  6.+0.j]]


In [33]:
#import pandas as pd
#df1=pd.read_csv("posts")

# numpy functions

In [34]:
a = np.array([[1,3,],[4,3],[5,9]],dtype=np.float64)
a.reshape(1,-1)
print (a)

[[ 1.  3.]
 [ 4.  3.]
 [ 5.  9.]]


In [35]:
print(a.min())
print(a.min(axis=1))      #for row
print(a.max())
print(a.max(axis=0))       #for columns
print(a.sum(axis=0))
print(a.sum(axis=1))
#print(a.sqrt(a))
#print(a.std(a))

1.0
[ 1.  3.  5.]
9.0
[ 5.  9.]
[ 10.  15.]
[  4.   7.  14.]


In [36]:
#a.std(a)

In [37]:
a.ravel()

array([ 1.,  3.,  4.,  3.,  5.,  9.])

In [38]:
np.sin(a)

array([[ 0.84147098,  0.14112001],
       [-0.7568025 ,  0.14112001],
       [-0.95892427,  0.41211849]])