In [112]:
#1. Create a null vector of size 10
import numpy as np
a=np.zeros(10)
print(a)



[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [113]:
#2. Create a null vector of size 10 but the fifth value which is 1
a[4]=1
print(a)


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [114]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
print(np.arange(9).reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [115]:
#4. Create a 10x10 array with random values and find the minimum and maximumvalues
a=np.random.random(100).reshape(10,10)
print(a)
print(np.min(a))
print(np.max(a))

[[ 0.10396439  0.0814899   0.65889009  0.57792948  0.56967249  0.18165899
   0.65618846  0.89009298  0.98091254  0.00853622]
 [ 0.90881268  0.23750129  0.54385313  0.84269439  0.75223506  0.17167376
   0.52665287  0.91143151  0.941489    0.97530056]
 [ 0.21779522  0.71316726  0.11782056  0.19560815  0.807319    0.33552761
   0.15555344  0.04609271  0.30165487  0.52843753]
 [ 0.41771848  0.12191624  0.17388138  0.48585338  0.40307922  0.4068069
   0.01163817  0.71842345  0.12017531  0.59451788]
 [ 0.63607615  0.73469856  0.02463024  0.77988591  0.85034247  0.1792026
   0.27691652  0.7258253   0.51173655  0.51226996]
 [ 0.88093007  0.90838604  0.74931615  0.6028814   0.44479236  0.07054689
   0.28092277  0.91490737  0.55887579  0.22997977]
 [ 0.19618084  0.9903236   0.58687347  0.2732252   0.35505588  0.62109865
   0.41959534  0.60386379  0.77576023  0.46913861]
 [ 0.62969932  0.03129954  0.17814025  0.78521007  0.72245912  0.91301706
   0.79328016  0.51070074  0.67998339  0.32122327]
 [

In [116]:
#5. Create a 3x3 identity matrix
print(np.eye(3,3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [117]:
#6. Create a random vector of size 30 and find the mean value

import pandas as pd
a=np.random.random(30)
print(a)
m=a.mean()
print(m)

[ 0.48063821  0.11196847  0.73826095  0.96904285  0.77861902  0.47076261
  0.6123805   0.24178747  0.0320505   0.88733656  0.09379208  0.69233352
  0.59561111  0.91004645  0.65705421  0.36335041  0.46803501  0.00815018
  0.63524348  0.47720576  0.22500231  0.7747836   0.36735854  0.27235525
  0.25119342  0.64295745  0.35868284  0.03002371  0.64310656  0.38077731]
0.472330344592


In [118]:
#7. Reverse a vector (first element becomes last)
a=np.arange(8)
print(a[::-1])

[7 6 5 4 3 2 1 0]


In [119]:
#8. Find indices of non-zero elements from [1,2,0,0,4,0]
print(np.array([1,2,0,0,4,0]).nonzero())


(array([0, 1, 4], dtype=int64),)


In [120]:
#9. Create a 2d array with 1 on the border and 0 inside
a=np.ones((4,4))
a[1:-1,1:-1] = 0
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  1.  1.  1.]]
